version: '3.8'

services:
  purchase-approval:
    build: .
    container_name: bank-purchase-app
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
        tag: "bank-purchase"
